# Generated by Django 4.0.4 on 2022-04-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klienci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_klienta', models.IntegerField(max_length=8)),
                ('numer_legitymacj', models.IntegerField(max_length=8)),
                ('create_time', models.TimeField()),
                ('stan_konta', models.FloatField(max_length=4)),
                ('sposob_dostawy', models.IntegerField()),
                ('sposob_platnosci', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_legitymacj', models.IntegerField(max_length=8)),
                ('active', models.IntegerField(max_length=1)),
                ('create_time', models.TimeField()),
                ('name', models.CharField(max_length=16)),
                ('surname', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('desc', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_zamowienia', models.IntegerField(max_length=8)),
                ('id_klienta', models.IntegerField(max_length=8)),
                ('stan_platnosci', models.IntegerField(max_length=1)),
                ('stan_zamowienia', models.IntegerField(max_length=1)),
                ('cena', models.FloatField()),
            ],
        ),
    ]
