# Generated by Django 4.0.4 on 2022-04-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klienci',
            name='create_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='create_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='numer_legitymacj',
            field=models.CharField(max_length=8),
        ),
    ]
