# Generated by Django 4.0.4 on 2022-04-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_food', '0002_alter_klienci_create_time_alter_users_create_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('opis', models.CharField(max_length=200)),
                ('ilosc', models.ImageField(upload_to='')),
                ('dostepnosc', models.BooleanField()),
                ('kategoria', models.CharField(max_length=100)),
                ('cena', models.IntegerField()),
            ],
        ),
    ]
