# Generated by Django 4.0.4 on 2022-04-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_food', '0003_dania'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dania',
            name='ilosc',
            field=models.IntegerField(max_length=100),
        ),
    ]
