# Generated by Django 4.0.4 on 2022-04-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_food', '0005_alter_dania_cena_alter_dania_ilosc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dania',
            name='create_time',
            field=models.DateTimeField(null=True),
        ),
    ]
