# Generated by Django 4.0.4 on 2022-04-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_food', '0007_dania_modify_time_alter_dania_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dania',
            name='modify_time',
            field=models.DateTimeField(),
        ),
    ]
